# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yuntse/work/coherent/LArTPCgeant4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yuntse/work/coherent/LArTPCgeant4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuntse/work/coherent/LArTPCgeant4/CMakeFiles /Users/yuntse/work/coherent/LArTPCgeant4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuntse/work/coherent/LArTPCgeant4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lartpc

# Build rule for target.
lartpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lartpc
.PHONY : lartpc

# fast build rule for target.
lartpc/fast:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/build
.PHONY : lartpc/fast

lartpc.o: lartpc.cc.o

.PHONY : lartpc.o

# target to build an object file
lartpc.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/lartpc.cc.o
.PHONY : lartpc.cc.o

lartpc.i: lartpc.cc.i

.PHONY : lartpc.i

# target to preprocess a source file
lartpc.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/lartpc.cc.i
.PHONY : lartpc.cc.i

lartpc.s: lartpc.cc.s

.PHONY : lartpc.s

# target to generate assembly for a file
lartpc.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/lartpc.cc.s
.PHONY : lartpc.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/EventRecord.o: src/EventRecord.cc.o

.PHONY : src/EventRecord.o

# target to build an object file
src/EventRecord.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventRecord.cc.o
.PHONY : src/EventRecord.cc.o

src/EventRecord.i: src/EventRecord.cc.i

.PHONY : src/EventRecord.i

# target to preprocess a source file
src/EventRecord.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventRecord.cc.i
.PHONY : src/EventRecord.cc.i

src/EventRecord.s: src/EventRecord.cc.s

.PHONY : src/EventRecord.s

# target to generate assembly for a file
src/EventRecord.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/EventRecord.cc.s
.PHONY : src/EventRecord.cc.s

src/MARLEYGenerator.o: src/MARLEYGenerator.cc.o

.PHONY : src/MARLEYGenerator.o

# target to build an object file
src/MARLEYGenerator.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/MARLEYGenerator.cc.o
.PHONY : src/MARLEYGenerator.cc.o

src/MARLEYGenerator.i: src/MARLEYGenerator.cc.i

.PHONY : src/MARLEYGenerator.i

# target to preprocess a source file
src/MARLEYGenerator.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/MARLEYGenerator.cc.i
.PHONY : src/MARLEYGenerator.cc.i

src/MARLEYGenerator.s: src/MARLEYGenerator.cc.s

.PHONY : src/MARLEYGenerator.s

# target to generate assembly for a file
src/MARLEYGenerator.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/MARLEYGenerator.cc.s
.PHONY : src/MARLEYGenerator.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/lartpc.dir/build.make CMakeFiles/lartpc.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... lartpc"
	@echo "... lartpc.o"
	@echo "... lartpc.i"
	@echo "... lartpc.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/EventRecord.o"
	@echo "... src/EventRecord.i"
	@echo "... src/EventRecord.s"
	@echo "... src/MARLEYGenerator.o"
	@echo "... src/MARLEYGenerator.i"
	@echo "... src/MARLEYGenerator.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

